### ISSUE TITLE
Remedy direct access of zmq_msg_t members.

### ISSUE THREAD

**Issue by digitalextremist** [chuckremes/ffi-rzmq-core#10]
Per comments on https://github.com/celluloid/celluloid-zmq/issues/56, we notice this gem is now fully compatible with `4.0+`...

With one exception:

> The API docs explicitly say not to use the zmsg struct, but ffi-rzmq-core does it.
> -- @Asmod4n

Reference: http://api.zeromq.org/4-0:zmq-msg-init

> Never access zmq_msg_t members directly, instead always use the zmq_msg family of functions.

@chuckremes is this an impossible to fix issue that the gem depends on, or can this be changed?

**Comment by paddor** [comment]
AFAICS, this isn't done (anymore). I checked both this repo and [ffi-rzmq](https://github.com/chuckremes/ffi-rzmq). Actually the only instance of LibZMQ::Message created in the two repositories is in spec/structures_spec.rb of this repo. Any members of it aren't accessed directly anywhere, as far as I can tell.

Can't speak for projects using this or the other repo, though.

**Comment by Asmod4n** [comment]
@digitalextremist this can be closed.

I apologize for what i said there, i believe that was never true.

What libzmq is simply missing is a way to say how large the opaque zmq_msg_t struct is.

**Comment by paddor** [comment]
@Asmod4n You can: Looking at the source of ffi-rzmq, you can just call `ZMQ::Message.msg_size` to get the size of the struct. See [here](https://github.com/chuckremes/ffi-rzmq/blob/master/lib/ffi-rzmq/message.rb#L196-L198) and [here](https://github.com/chuckremes/ffi-rzmq-core/blob/master/lib/ffi-rzmq-core/structures.rb#L5-L19).

But I guess that's not actually what you mean. From libzmq itself? Maybe not. But it doesn't seem to have varied in size for a long time.

**Comment by Asmod4n** [comment]
@paddor 
It has changed 3-4 times so far.
The problem is: libzmq never returns that type afaik and expects it as a parameter.
FFI has no idea about types, all it can do is call functions. If you want to introduce a type to FFI you have to do it on your own.

I belive this is called a chicken/egg Problem.

libzmq expects a zmq_msg_t as a paremeter, which is a opague pointer. FFI has no idea zmq_msg_t exists so you have to introduce that type to it somehow. So to create that type in FFI you have to tell it how large it is but libzmq isn't telling you how large it is.

**Comment by chuckremes** [comment]
True, but not completely true. From the libzmq headers we can see how much memory is allocated to the zmq_msg_t struct. It has gone from 32 to 64 bytes over the last several years. As long as we allocate the proper number of bytes then we are fine. No one is supposed to be accessing the zmq_msg_t struct members directly, so making sure that we have the proper field names is irrelevant.

We are allocating sufficient memory, so that’s as far as we need to take this.

**Comment by skaes** [comment]
Please have a look at https://github.com/chuckremes/ffi-rzmq-core/pull/14
