### ISSUE TITLE
Missing symbols with zmq 4.2.0

### ISSUE THREAD

**Issue by nullobject** [chuckremes/ffi-rzmq-core#15]
Running the latest zeromq (4.2.0) when installed from brew throws this error when I try to open a connection:

```
dyld: lazy symbol binding failed: Symbol not found: _randombytes
  Referenced from: /usr/local/lib/libzmq.dylib
  Expected in: flat namespace

dyld: Symbol not found: _randombytes
  Referenced from: /usr/local/lib/libzmq.dylib
  Expected in: flat namespace
```

**Comment by csaura** [comment]
The same happens to me. I'm on MacOS Sierra with ruby 2.3.1 .

**Comment by chuckremes** [comment]
@nullobject  @csaura  Give me some example code that reproduces the error and I'll get it fixed. I haven't seen this problem.

**Comment by lsdriscoll** [comment]
Also having this issue. All I did was `brew install zmq`

**Comment by bilus** [comment]
Same here after `brew install zeromq` (4.2.2).

**Comment by amisukanta** [comment]
Same thing happened to me, i solved it by installing zeromq (4.0)
`brew install zeromq40`

**Comment by spinlock99** [comment]
I had the same issue. Unfortunately, @amisukanta's solution did not work for me. But, I was able to download the 4.2.1 tarball and simply run `./configure; make; make install`. 

system: macOS Sierra v10.12.3
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]

**Comment by amisukanta** [comment]
@spinlock99 thanks for your response with solution, I did not try it with version 4.2.1

But this thread is helpful for sure 😆

**Comment by chuckremes** [comment]
Looks like this is caused by `libsodium` being part of the default brew recipe. But it isn't listed as a dependency so brew lets you install zeromq and then fails to link because lib sodium is missing. 

I think this is a brew bug. But @spinlock99's solution should work too since it will be pretty explicit about how to build zeromq. You have to pass a flag to enable libsodium so the system will complain if you don't have it available.

I'll leave this open until it's clear that brew has fixed the recipe.

**Comment by chuckremes** [comment]
Closed due to fix in home-brew (see: https://github.com/Homebrew/homebrew-core/pull/13696).
