### ISSUE TITLE
LibZMQ::Message.size is smaller than in latest zeromq4-1 release.

### ISSUE THREAD

**Issue by jemc** [chuckremes/ffi-rzmq-core#8]
`zmq_msg_t` is now [64 bytes](https://github.com/zeromq/libzmq/commit/90194036bf824d78e13955ab931a70e929d356c1) on all platforms.  On my machine, `LibZMQ::Message.size == 40`, causing nasty SEGVs when `zmq_msg_*` functions run into memory that wasn't allocated by Ruby FFI properly (because the buffer allocated was too small).

I'm not sure what the best way to address this is, in keeping compatibility with other versions of zeromq, but this is definitely a problem for at least `4.1.3`.

**Comment by chuckremes** [comment]
Hmmm, okay. I’ll try to look at this on Monday/Tuesday and come up with a fix.

Thank you for the report.

**Comment by timmyArch** [comment]
Hey, i think this issue could be closed, the problem should fixed since latest pull request.

**Comment by chuckremes** [comment]
I changed the code (after the pull request) to allow for backward compatibility. There are probably some folks out there using libzmq 3.x and earlier releases of 4.0. No need to abandon them when the change is easy. Updated and pushed.

**Comment by rj45** [comment]
So :content should be :vsm_size in the "backward compatibility" update, I think that's just a simple typo.

**Comment by chuckremes** [comment]
The field :vsm_size is already listed in that structure, so replacing :content with :vsm_size doesn’t make sense.

Is this causing a problem?

**Comment by chuckremes** [comment]
Take a look here:

https://github.com/zeromq/zeromq2-x/blob/master/include/zmq.h#L172

The “backward compatible” struct is mimicking that layout. However, no one should be trying to access any zmq_msg_t fields directly anyway. They should always use the zmq_msg_* functions that are part of the API. I’m confident that ffi-rzmq does that in all cases, so the naming of these fields is unimportant.

The important part is that the message structure allocates the correct amount of data. Through the life of the zeromq project, it has gone from 32 to 40 to 48 to 64 bytes.

Hope this clarifies.

**Comment by rj45** [comment]
Well I don't really know what I am talking about so I shouldn't suggest solutions.

The issue is that the pull request code works (ish... it doesn't crash anymore anyway but I think the message size is still wrong), but the backwards compatible modification in the official gem does not work. LibZMQ::Message.size == 40 is still true on ZMQ 4.1.3. I believe it should be LibZMQ::Message.size == 64. We hacked the source and generated a gem to make it 64 and it seems to work fine, no more SEGV crashes. I haven't 100% verified that is true, but I will report it here if it has continued to crash on us.

It would be nice if a public version had this fixed, but we have a custom gem we built now that we can use so it's not super urgent or anything.

**Comment by roosterfive** [comment]
I still see this issue exactly as described by the OP. Using x86_64-linux, ffi-rzmq-core(1.0.4), libzmq (4.1.3, 4.1.4), ruby(2.2.4p230)

With the 1.0.4 fix, the LibZMQ::Message class allocates 40 bytes for all libzmq versions but the class is reopened for libzmq versions 4.1+ so layout() is called a second time. The new layout ostensibly allocates 64 bytes but erroneously calls for only 8 bytes to be allocated (by using a :ulong_long).  However, only 40 bytes are ultimately allocated because the layout size was previously set to 40 in the first call to layout and will not be updated if the new size (8) is less than the existing size (40).

Note that this allocation problem was not flagged by the tests (structures_spec) because the test itself was in error.

Please see pull request #11 for a simple fix that is working for me.
